Create popup module for the work section.
Omwomo/Portfolio pull request #8
Opened 2023-06-21 13:43 UTC by Omwomo

##When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
##When the user clicks (or taps) the close X button, the popup disappears.
##Created a JavaScript object to store name, description, featured image, technologies, link to live version, link to source
##Updated the main page so that the projects section is created dynamically using the information stored in the JavaScript object I created.
##Styled the popup module according to the figma template.

2023-06-21 15:23 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @Omwomo 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- Descriptive PR title ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 15:23 UTC, AbelG101 commented on index.html
https://github.com/Omwomo/Microverse-web-portfolio-project/blob/fcff5a94994c2d401b2056b460f18ba3b1cf2291/index.html#L59-L255
- [ ] You've done well implementing the pop-up but you seem to be missing one of the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) that states that you need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. This means all the above HTML code should be removed from the HTML file and only be created dynamically using the array of project objects in your JS file. ✔

2023-06-21 15:23 UTC, AbelG101 commented on script.js
> +});
- [ ] There seems to be a bit of a bug here as the popup is being displayed when the page loads and this causes a bad UX so please make sure to fix this.
- Here's how it currently behaves:
  ![firefox_4XvhHLn1lE](https://github.com/Omwomo/Microverse-web-portfolio-project/assets/104968236/47a4d748-17f7-460d-aa09-bb4da2933a3f)

2023-06-21 15:23 UTC, AbelG101 commented on script.js
> +];
- [ ] Please make sure you're following the DRY (don't repeat yourself) principle when programming as I noticed an unnecessary duplication of the projects array here you only need one project array for both mobile and desktop as they represent the same project. ✔
- [ ] This also means you also need to refactor the 2 popup functions you have `openPopup()` and `openPopups()` on line 96 & 127

2023-06-21 15:23 UTC, AbelG101 commented on img/git.svg
- [ ] Kindly make sure to remove the below text from your README file as it's part of a section description that is only meant to guide the author and should be removed from the final draft. ✔
    ![image](https://github.com/Omwomo/Microverse-web-portfolio-project/assets/104968236/5a80e7cd-009e-4c7b-91a2-7783d3cde1b5)

2023-06-22 09:23 UTC, LionRouge1 approved these changes
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-06-22 09:33 UTC, Omwomo commented
Restructured the project section by moving it from HTML to populate it dynamically using JavaScript. And also added the popup module.

2023-06-22 09:33 UTC, merged